spring:
  datasource:
    url: jdbc:mysql://121.251.255.96:3306/yibantest_production
    username: yibantest
    password: yibantest
    test-while-idle: true
    validation-query: SELECT 1
  thymeleaf:
    mode: LEGACYHTML5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8086
yibanoauth:
  bulletinboard:
    APPID: "acaec190548725cf"
    APPkey: "6b7d82af041da97d586ad8b8d8204225"
  calendar:
     APPID: "d909b5b12fd5edec"
     APPkey: "6f5d239396df74e4672932d8ede57beb"
  lottery:
    APPID: "acaec190548725cf"
    APPkey: "6b7d82af041da97d586ad8b8d8204225"
  lostandfound:
     APPID: "2f803dad07f95108"
     APPkey: "f732a9b113713c3e1f85a85b6b1282b8"
  second:
      APPID: "d3e9e3722272dc94"
      APPkey: "202f365322d008bab2f76d5eea1bfb15"
      frontend: "http://localhost:4000"
      imgserver: "http://localhost:8080"
  express:
      APPID: "fbea79f78cbe9fef"
      APPkey: "cd1d99b207c0050317798f8393e20968"
  deliverwater:
      APPID: "c5295b6cf87a2c99"
      APPkey: "64de90bef3677e54e22e6ed1766f1067"
  homepage:
      APPID: "783d63c193f94aa2"
      APPkey: "3d8b2b3508d5210b70b121b299fbd6af"
  ballot:
      APPID: "f502ec585b349e79"
      APPkey: "9c80931a3d7b060b927658b8a9461223"
  material:
      APPID: "f87c99a7211f2a44"
      APPkey: "ce7a947563254450913c4b768dc76b9e"
  speaktoteacher:
      APPID: "f502ec585b349e79"
      APPkey: "9c80931a3d7b060b927658b8a9461223"
  deliciousfood:
      APPID: "14a69e60117cbef1"
      APPkey: "459e5e748ad9871893b2a9e016e9483a"
